version: '3'
services:
  jenkins:
    container_name: jenkins2
    # docker pull from official repo.
    image: jenkins-ansible
    build:
      context: jenkins-ansible
    ports:
      - "8080:8080"
    # shared directory(local directory:container directory)
    volumes:
      - "$PWD/jenkins_home:/var/jenkins_home"
    networks:
      - net
  remote_host:
    container_name: remote-host
    image: remote-host
    # indicate which Dockerfile to build
    build:
      # relative path
      context: centos7
    volumes:
      - "$PWD/aws-s3.sh:/tmp/script.sh"
    networks:
      - net
  db_host:
    container_name: db
    image: mysql:5.7
    environment: 
      - "MYSQL_ROOT_PASSWORD=1234"
      # persistent shared folder
    volumes: 
      - "$PWD/db_data:/var/lib/mysql"
    networks:
      - net
networks:
  net: