-
    name: 'Execute a script on all web server nodes'
    hosts: all_servers
    tasks:
        -
            service: 'name=mysql state=started'
            #文字列の場合はダブルクオテーションで囲む
            when: 'ansible_host=="server4.company.com"'
