## サンプルコード
##   TCP-SOCKET ヘルスチェック 
apiVersion: v1
kind: Pod
metadata:
  name: probe-tcp-port
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
    readinessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 10
      periodSeconds: 10
    livenessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
