apiVersion: batch/v1
kind: Job
metadata:
  name: abnormal-end
spec:
  template:
    spec:
      containers:
      - name: busybox1
        image: busybox:latest
        command: ["sh",  "-c", "sleep 5; exit 0"]
      - name: busybox2
        image: busybox:latest
        command: ["sh",  "-c", "sleep 5; exit 1"]
      restartPolicy: Never
    backoffLimit: 2