##
# アプリ開発者用のサービスアカウント(SA)を作成
#
apiVersion: v1
kind: ServiceAccount
metadata:
  name: developer
  namespace: test
---
################################################
##
# アプリ開発者SAを「クラスタロールADMIN」を対応づけ
#
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-crb
  namespace: test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  namespace: test
  name: developer

##---
##
# アプリ開発者 ロールの作成
#   クラスタロール admin に含まれるので任意
#
##apiVersion: rbac.authorization.k8s.io/v1
##kind: Role
##metadata:
##  name: developer
##  namespace: test
##rules:
# ポッドのアクセス権 コアAPIを指定 apiVersion: v1
##- apiGroups: [""]
##  resources: ["pods","pods/log","services"]
##  verbs: ["get", "watch", "list"]
# deploymentのアクセス権  extention/applsを指定
##- apiGroups: ["extensions", "apps"]  
## resources: ["deployments"]
##  verbs: ["get", "watch", "list"]

---
##
# アプリ開発者SAと「ロールdeveloper」を対応づけ
#   (クラスタロール admin に含まれるので任意)
#
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-rb
  namespace: test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: developer
subjects:
- kind: ServiceAccount
  namespace: test
  name: developer

