#
# 外部公開用 模擬
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-apl1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        web: web-apl1
        app: expose          # 外部公開用ラベル
    spec:
      containers:
      - image: maho/webapl3  # 模擬用アプリ
        name: web-server-c
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-apl1
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
  selector:
    web: web-apl1
