## k8sノードをリセット
#
- name: kubeadm reset
  command: kubeadm reset -f

## k8sクラスタへ参加
#
- name: copy from home to local
  copy:
    src: /vagrant/kubeadm-join.tmp
    dest: /tmp/kubeadm-join.yaml
- name: include kubeadm join token etc
  include_vars: /tmp/kubeadm-join.yaml
- name: kubeadm join
  command: "{{ join_command }}"  

## kubeletのDNSのIPアドレスを変更
#
- name: change config.yaml
  replace:
    dest: /var/lib/kubelet/config.yaml
    regexp: '10.96.0.10'
    replace: 10.32.0.10

## kubeletをリスタートして変更を反映
#
- name: daemon-reload and restart kubelet
  systemd:
    state: restarted
    daemon_reload: yes
    name: kubelet
