apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep1pod-blk
  labels:
    app: dep1pod-blk
spec:
  selector:
    matchLabels:
      app: dep1pod-blk
  template:
    metadata:
      labels:
        app: dep1pod-blk
    spec:
      containers:    
      - image: ubuntu
        name: ubuntu
        volumeMounts:
        - name: blk
          mountPath: /mnt
        command: ["/usr/bin/tail","-f","/dev/null"]	  
      volumes:              ## ポッドのボリューム定義
      - name: blk
        persistentVolumeClaim:
          claimName: bronze-blk

